In [4]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [ ]:
DIABETES_PATH = "../data/raw/diabetes_prediction_dataset.csv"
HEART_PATH = "../data/raw/cardio_train.csv"
KIDNEY_PATH = "../data/raw/Chronic_Kidney_Disease_data.csv"

In [6]:
diabetes_df = pd.read_csv(DIABETES_PATH)

heart_df = pd.read_csv(
    HEART_PATH,
    sep=";"
)

kidney_df = pd.read_csv(KIDNEY_PATH)

In [7]:
print("Diabetes Dataset Shape :", diabetes_df.shape)

print("Heart Dataset Shape :", heart_df.shape)

print("Kidney Dataset Shape :", kidney_df.shape)

Diabetes Dataset Shape : (100000, 9)
Heart Dataset Shape : (70000, 13)
Kidney Dataset Shape : (1659, 54)

In [8]:
print("Diabetes Dataset")
display(diabetes_df.head())

print("Heart Dataset")
display(heart_df.head())

print("Kidney Dataset")
display(kidney_df.head())

Diabetes Dataset

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

Heart Dataset

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

Kidney Dataset

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,FamilyHistoryKidneyDisease,FamilyHistoryHypertension,FamilyHistoryDiabetes,PreviousAcuteKidneyInjury,UrinaryTractInfections,SystolicBP,DiastolicBP,FastingBloodSugar,HbA1c,SerumCreatinine,BUNLevels,GFR,ProteinInUrine,ACR,SerumElectrolytesSodium,SerumElectrolytesPotassium,SerumElectrolytesCalcium,SerumElectrolytesPhosphorus,HemoglobinLevels,CholesterolTotal,CholesterolLDL,CholesterolHDL,CholesterolTriglycerides,ACEInhibitors,Diuretics,NSAIDsUse,Statins,AntidiabeticMedications,Edema,FatigueLevels,NauseaVomiting,MuscleCramps,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
0,1,71,0,0,0,2,31.069414,1,5.128112,1.676220,0.240386,4.076434,0,0,0,0,0,113,83,72.510788,9.212397,4.962531,25.605949,45.703204,0.744980,123.849426,137.652501,3.626058,10.314420,3.152648,16.114679,207.728670,85.863656,21.967957,212.095215,0,0,4.563139,1,0,0,3.563894,6.992244,4.518513,7.556302,76.076800,0,0,1,1.018824,4.966808,9.871449,1,Confidential
1,2,34,0,0,1,3,29.692119,1,18.609552,8.377574,6.503233,7.652813,1,1,0,0,0,120,67,100.848875,4.604989,3.156799,31.338166,55.784504,3.052317,88.539095,138.141335,5.332871,9.604196,2.855443,15.349205,189.450727,86.378670,87.569756,255.451314,0,0,9.097002,0,0,0,5.327336,0.356290,2.202222,6.836766,40.128498,0,0,0,3.923538,8.189275,7.161765,1,Confidential
2,3,80,1,1,0,1,37.394822,1,11.882429,9.607401,2.104828,4.392786,0,0,0,0,0,147,106,160.989441,5.432599,3.698236,39.738169,67.559032,1.157839,21.170892,142.970116,4.330891,9.885786,4.353513,13.018834,284.137622,132.269872,20.049798,251.902583,0,1,3.851249,1,0,0,4.855420,4.674069,5.967271,2.144722,92.872842,0,1,1,1.429906,7.624028,7.354632,1,Confidential
3,4,40,0,2,0,1,31.329680,0,16.020165,0.408871,6.964422,6.282274,0,0,0,0,0,117,65,188.506620,4.144466,2.868468,21.980958,33.202542,3.745871,123.779699,137.106913,3.810741,9.995894,4.016134,15.056339,235.112124,93.443669,58.260291,392.338425,0,0,7.881765,0,0,0,8.531685,5.691455,2.176387,7.077188,90.080321,0,0,0,3.226416,3.282688,6.629587,1,Confidential
4,5,43,0,1,1,2,23.726311,0,7.944146,0.780319,3.097796,4.021639,0,0,0,0,0,98,66,82.156699,4.262979,3.964877,12.216366,56.319082,2.570993,184.852046,140.627812,4.866765,8.907622,3.947907,16.690561,258.277566,171.758356,21.583213,370.523877,1,1,4.179459,1,0,0,1.422320,2.273459,6.800993,3.553118,5.258372,0,0,1,0.285466,3.849498,1.437385,1,Confidential

In [9]:
print("Diabetes Columns")
print(diabetes_df.columns.tolist())

print("\nHeart Columns")
print(heart_df.columns.tolist())

print("\nKidney Columns")
print(kidney_df.columns.tolist())

Diabetes Columns
['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes']

Heart Columns
['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio']

Kidney Columns
['PatientID', 'Age', 'Gender', 'Ethnicity', 'SocioeconomicStatus', 'EducationLevel', 'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality', 'SleepQuality', 'FamilyHistoryKidneyDisease', 'FamilyHistoryHypertension', 'FamilyHistoryDiabetes', 'PreviousAcuteKidneyInjury', 'UrinaryTractInfections', 'SystolicBP', 'DiastolicBP', 'FastingBloodSugar', 'HbA1c', 'SerumCreatinine', 'BUNLevels', 'GFR', 'ProteinInUrine', 'ACR', 'SerumElectrolytesSodium', 'SerumElectrolytesPotassium', 'SerumElectrolytesCalcium', 'SerumElectrolytesPhosphorus', 'HemoglobinLevels', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL', 'CholesterolTriglycerides', 'ACEInhibitors', 'Diuretics', 'NSAIDsUse', 'Statins', 'AntidiabeticMedications', 'Edema', 'FatigueLevels', 'NauseaVomiting', 'MuscleCramps', 'Itching', 'QualityOfLifeScore', 'HeavyMetalsExposure', 'OccupationalExposureChemicals', 'WaterQuality', 'MedicalCheckupsFrequency', 'MedicationAdherence', 'HealthLiteracy', 'Diagnosis', 'DoctorInCharge']

In [10]:
print("========== Diabetes ==========")
diabetes_df.info()

print("\n========== Heart ==========")
heart_df.info()

print("\n========== Kidney ==========")
kidney_df.info()

========== Diabetes ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

========== Heart ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

========== Kidney ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PatientID                      1659 non-null   int64
 1   Age                            1659 non-null   int64
 2   Gender                         1659 non-null   int64
 3   Ethnicity                      1659 non-null   int64
 4   SocioeconomicStatus            1659 non-null   int64
 5   EducationLevel                 1659 non-null   int64
 6   BMI                            1659 non-null   float64
 7   Smoking                        1659 non-null   int64
 8   AlcoholConsumption             1659 non-null   float64
 9   PhysicalActivity               1659 non-null   float64
 10  DietQuality                    1659 non-null   float64
 11  SleepQuality                   1659 non-null   float64
 12  FamilyHistoryKidneyDisease     1659 non-null   int64
 13  FamilyHistoryHypertension      1659 non-null   int64
 14  FamilyHistoryDiabetes          1659 non-null   int64
 15  PreviousAcuteKidneyInjury      1659 non-null   int64
 16  UrinaryTractInfections         1659 non-null   int64
 17  SystolicBP                     1659 non-null   int64
 18  DiastolicBP                    1659 non-null   int64
 19  FastingBloodSugar              1659 non-null   float64
 20  HbA1c                          1659 non-null   float64
 21  SerumCreatinine                1659 non-null   float64
 22  BUNLevels                      1659 non-null   float64
 23  GFR                            1659 non-null   float64
 24  ProteinInUrine                 1659 non-null   float64
 25  ACR                            1659 non-null   float64
 26  SerumElectrolytesSodium        1659 non-null   float64
 27  SerumElectrolytesPotassium     1659 non-null   float64
 28  SerumElectrolytesCalcium       1659 non-null   float64
 29  SerumElectrolytesPhosphorus    1659 non-null   float64
 30  HemoglobinLevels               1659 non-null   float64
 31  CholesterolTotal               1659 non-null   float64
 32  CholesterolLDL                 1659 non-null   float64
 33  CholesterolHDL                 1659 non-null   float64
 34  CholesterolTriglycerides       1659 non-null   float64
 35  ACEInhibitors                  1659 non-null   int64
 36  Diuretics                      1659 non-null   int64
 37  NSAIDsUse                      1659 non-null   float64
 38  Statins                        1659 non-null   int64
 39  AntidiabeticMedications        1659 non-null   int64
 40  Edema                          1659 non-null   int64
 41  FatigueLevels                  1659 non-null   float64
 42  NauseaVomiting                 1659 non-null   float64
 43  MuscleCramps                   1659 non-null   float64
 44  Itching                        1659 non-null   float64
 45  QualityOfLifeScore             1659 non-null   float64
 46  HeavyMetalsExposure            1659 non-null   int64
 47  OccupationalExposureChemicals  1659 non-null   int64
 48  WaterQuality                   1659 non-null   int64
 49  MedicalCheckupsFrequency       1659 non-null   float64
 50  MedicationAdherence            1659 non-null   float64
 51  HealthLiteracy                 1659 non-null   float64
 52  Diagnosis                      1659 non-null   int64
 53  DoctorInCharge                 1659 non-null   object
dtypes: float64(30), int64(23), object(1)
memory usage: 700.0+ KB

In [11]:
print("Diabetes")
display(diabetes_df.dtypes)

print("Heart")
display(heart_df.dtypes)

print("Kidney")
display(kidney_df.dtypes)

Diabetes

gender                  object
age                    float64
hypertension             int64
heart_disease            int64
smoking_history         object
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

Heart

id               int64
age              int64
gender           int64
height           int64
weight         float64
ap_hi            int64
ap_lo            int64
cholesterol      int64
gluc             int64
smoke            int64
alco             int64
active           int64
cardio           int64
dtype: object

Kidney

PatientID                          int64
Age                                int64
Gender                             int64
Ethnicity                          int64
SocioeconomicStatus                int64
EducationLevel                     int64
BMI                              float64
Smoking                            int64
AlcoholConsumption               float64
PhysicalActivity                 float64
DietQuality                      float64
SleepQuality                     float64
FamilyHistoryKidneyDisease         int64
FamilyHistoryHypertension          int64
FamilyHistoryDiabetes              int64
PreviousAcuteKidneyInjury          int64
UrinaryTractInfections             int64
SystolicBP                         int64
DiastolicBP                        int64
FastingBloodSugar                float64
HbA1c                            float64
SerumCreatinine                  float64
BUNLevels                        float64
GFR                              float64
ProteinInUrine                   float64
ACR                              float64
SerumElectrolytesSodium          float64
SerumElectrolytesPotassium       float64
SerumElectrolytesCalcium         float64
SerumElectrolytesPhosphorus      float64
HemoglobinLevels                 float64
CholesterolTotal                 float64
CholesterolLDL                   float64
CholesterolHDL                   float64
CholesterolTriglycerides         float64
ACEInhibitors                      int64
Diuretics                          int64
NSAIDsUse                        float64
Statins                            int64
AntidiabeticMedications            int64
Edema                              int64
FatigueLevels                    float64
NauseaVomiting                   float64
MuscleCramps                     float64
Itching                          float64
QualityOfLifeScore               float64
HeavyMetalsExposure                int64
OccupationalExposureChemicals      int64
WaterQuality                       int64
MedicalCheckupsFrequency         float64
MedicationAdherence              float64
HealthLiteracy                   float64
Diagnosis                          int64
DoctorInCharge                    object
dtype: object

In [12]:
print("Diabetes")
display(diabetes_df.describe(include="all"))

print("Heart")
display(heart_df.describe(include="all"))

print("Kidney")
display(kidney_df.describe(include="all"))

Diabetes

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000,100000.000000,100000.00000,100000.000000,100000,100000.000000,100000.000000,100000.000000,100000.000000
unique,3,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN
top,Female,NaN,NaN,NaN,No Info,NaN,NaN,NaN,NaN
freq,58552,NaN,NaN,NaN,35816,NaN,NaN,NaN,NaN
mean,NaN,41.885856,0.07485,0.039420,NaN,27.320767,5.527507,138.058060,0.085000
std,NaN,22.516840,0.26315,0.194593,NaN,6.636783,1.070672,40.708136,0.278883
min,NaN,0.080000,0.00000,0.000000,NaN,10.010000,3.500000,80.000000,0.000000
25%,NaN,24.000000,0.00000,0.000000,NaN,23.630000,4.800000,100.000000,0.000000
50%,NaN,43.000000,0.00000,0.000000,NaN,27.320000,5.800000,140.000000,0.000000
75%,NaN,60.000000,0.00000,0.000000,NaN,29.580000,6.200000,159.000000,0.000000
max,NaN,80.000000,1.00000,1.000000,NaN,95.690000,9.000000,300.000000,1.000000

Heart

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

Kidney

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,FamilyHistoryKidneyDisease,FamilyHistoryHypertension,FamilyHistoryDiabetes,PreviousAcuteKidneyInjury,UrinaryTractInfections,SystolicBP,DiastolicBP,FastingBloodSugar,HbA1c,SerumCreatinine,BUNLevels,GFR,ProteinInUrine,ACR,SerumElectrolytesSodium,SerumElectrolytesPotassium,SerumElectrolytesCalcium,SerumElectrolytesPhosphorus,HemoglobinLevels,CholesterolTotal,CholesterolLDL,CholesterolHDL,CholesterolTriglycerides,ACEInhibitors,Diuretics,NSAIDsUse,Statins,AntidiabeticMedications,Edema,FatigueLevels,NauseaVomiting,MuscleCramps,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
count,1659.000000,1659.000000,1659.000000,1659.00000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659.000000,1659
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Confidential
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1659
mean,830.000000,54.441230,0.515371,0.71308,0.977697,1.693189,27.620049,0.292948,9.969831,5.024247,5.028544,6.942324,0.141049,0.301386,0.257384,0.105485,0.210368,134.392405,89.313442,132.529429,6.983682,2.753198,27.578147,66.829202,2.493736,149.881615,139.968984,4.505336,9.489156,3.505543,13.927304,224.251158,125.044597,60.746861,224.804603,0.295359,0.318264,5.011715,0.380952,0.202532,0.201929,5.016697,3.482121,3.525510,5.054869,49.730659,0.044002,0.103074,0.197107,2.000336,4.947788,5.144973,0.918626,NaN
std,479.056364,20.549757,0.499914,1.00043,0.776686,0.910611,7.288670,0.455252,5.798787,2.866274,2.865777,1.704159,0.348177,0.458998,0.437325,0.307270,0.407693,25.767794,17.354479,36.563035,1.734714,1.317168,12.808062,30.050836,1.449695,86.850287,2.905595,0.583963,0.574849,0.576634,2.338372,43.666586,42.645021,23.170415,100.321757,0.456341,0.465943,2.869813,0.485767,0.402007,0.401560,2.896311,1.986292,2.026131,2.880460,27.827593,0.205162,0.304147,0.397934,1.141635,2.869959,2.901138,0.273492,NaN
min,1.000000,20.000000,0.000000,0.00000,0.000000,0.000000,15.033888,0.000000,0.021740,0.001186,0.002407,4.001053,0.000000,0.000000,0.000000,0.000000,0.000000,90.000000,60.000000,70.044768,4.000405,0.501799,5.000249,15.107850,0.000900,0.178427,135.006489,3.503408,8.500033,2.503727,10.004223,150.015707,50.074597,20.030993,50.267668,0.000000,0.000000,0.000469,0.000000,0.000000,0.000000,0.015194,0.005171,0.006327,0.013697,0.087256,0.000000,0.000000,0.000000,0.001082,0.005392,0.004436,0.000000,NaN
25%,415.500000,36.000000,0.000000,0.00000,0.000000,1.000000,21.471449,0.000000,5.051156,2.555038,2.558443,5.487083,0.000000,0.000000,0.000000,0.000000,0.000000,113.000000,75.000000,100.504503,5.494988,1.583255,16.398275,41.149324,1.226335,76.784343,137.483563,3.993559,9.004488,2.984834,11.839478,186.440971,87.660348,41.252078,140.235507,0.000000,0.000000,2.619890,0.000000,0.000000,0.000000,2.464695,1.750661,1.820793,2.532867,26.991708,0.000000,0.000000,0.000000,1.005802,2.498119,2.569561,1.000000,NaN
50%,830.000000,54.000000,1.000000,0.00000,1.000000,2.000000,27.652077,0.000000,9.951503,5.072395,4.989810,6.933255,0.000000,0.000000,0.000000,0.000000,0.000000,134.000000,89.000000,131.478423,6.988001,2.732006,28.077796,66.555207,2.505260,150.195312,139.863171,4.505416,9.470789,3.511712,13.909388,223.202106,126.537520,61.845056,226.466365,0.000000,0.000000,5.078511,0.000000,0.000000,0.000000,5.117247,3.519894,3.572522,5.087086,48.970075,0.000000,0.000000,0.000000,2.040635,4.974069,5.182949,1.000000,NaN
75%,1244.500000,72.000000,1.000000,1.00000,2.000000,2.000000,34.015849,1.000000,14.967100,7.460563,7.428290,8.346298,0.000000,1.000000,1.000000,0.000000,0.000000,157.000000,104.000000,163.108151,8.523562,3.889830,38.127391,92.388269,3.748696,225.057873,142.534461,5.022982,9.983515,4.009621,16.012084,262.681917,159.887298,80.388199,309.782788,1.000000,1.000000,7.485980,1.000000,0.000000,0.000000,7.565993,5.253156,5.254956,7.552093,73.913997,0.000000,0.000000,0.000000,2.947213,7.499783,7.733253,1.000000,NaN
max,1659.000000,90.000000,1.000000,3.00000,2.000000,3.000000,39.993532,1.000000,19.992713,9.998167,9.998927,9.984197,1.000000,1.000000,1.000000,1.000000,1.000000,179.000000,119.000000,199.960429,9.998393,4.998637,49.990522,119.920261,4.996343,299.580019,144.987495,5.499781,10.499944,4.498314,17.999656,299.950846,199.909911,99.987304,399.919138,1.000000,1.000000,9.999397,1.000000,1.000000,1.000000,9.988238,6.997332,6.984636,9.998313,99.987510,1.000000,1.000000,1.000000,3.999469,9.992345,9.993754,1.000000,NaN

In [13]:
print("Diabetes Missing Values")
display(diabetes_df.isnull().sum())

print("\nHeart Missing Values")
display(heart_df.isnull().sum())

print("\nKidney Missing Values")
display(kidney_df.isnull().sum())

Diabetes Missing Values

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

Heart Missing Values

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

Kidney Missing Values

PatientID                        0
Age                              0
Gender                           0
Ethnicity                        0
SocioeconomicStatus              0
EducationLevel                   0
BMI                              0
Smoking                          0
AlcoholConsumption               0
PhysicalActivity                 0
DietQuality                      0
SleepQuality                     0
FamilyHistoryKidneyDisease       0
FamilyHistoryHypertension        0
FamilyHistoryDiabetes            0
PreviousAcuteKidneyInjury        0
UrinaryTractInfections           0
SystolicBP                       0
DiastolicBP                      0
FastingBloodSugar                0
HbA1c                            0
SerumCreatinine                  0
BUNLevels                        0
GFR                              0
ProteinInUrine                   0
ACR                              0
SerumElectrolytesSodium          0
SerumElectrolytesPotassium       0
SerumElectrolytesCalcium         0
SerumElectrolytesPhosphorus      0
HemoglobinLevels                 0
CholesterolTotal                 0
CholesterolLDL                   0
CholesterolHDL                   0
CholesterolTriglycerides         0
ACEInhibitors                    0
Diuretics                        0
NSAIDsUse                        0
Statins                          0
AntidiabeticMedications          0
Edema                            0
FatigueLevels                    0
NauseaVomiting                   0
MuscleCramps                     0
Itching                          0
QualityOfLifeScore               0
HeavyMetalsExposure              0
OccupationalExposureChemicals    0
WaterQuality                     0
MedicalCheckupsFrequency         0
MedicationAdherence              0
HealthLiteracy                   0
Diagnosis                        0
DoctorInCharge                   0
dtype: int64

In [14]:
print("Diabetes Duplicates :", diabetes_df.duplicated().sum())

print("Heart Duplicates :", heart_df.duplicated().sum())

print("Kidney Duplicates :", kidney_df.duplicated().sum())

Diabetes Duplicates : 3854
Heart Duplicates : 0
Kidney Duplicates : 0

In [15]:
for name, df in {
    "Diabetes": diabetes_df,
    "Heart": heart_df,
    "Kidney": kidney_df
}.items():
    
    print("="*60)
    print(name)
    print("="*60)

    display(df.nunique().sort_values())

============================================================
Diabetes
============================================================

heart_disease             2
hypertension              2
diabetes                  2
gender                    3
smoking_history           6
blood_glucose_level      18
HbA1c_level              18
age                     102
bmi                    4247
dtype: int64

============================================================
Heart
============================================================

gender             2
active             2
alco               2
smoke              2
cardio             2
cholesterol        3
gluc               3
height           109
ap_hi            153
ap_lo            157
weight           287
age             8076
id             70000
dtype: int64

============================================================
Kidney
============================================================

DoctorInCharge                      1
Gender                              2
FamilyHistoryDiabetes               2
Smoking                             2
FamilyHistoryKidneyDisease          2
FamilyHistoryHypertension           2
UrinaryTractInfections              2
PreviousAcuteKidneyInjury           2
Diuretics                           2
Edema                               2
HeavyMetalsExposure                 2
OccupationalExposureChemicals       2
AntidiabeticMedications             2
Statins                             2
ACEInhibitors                       2
WaterQuality                        2
Diagnosis                           2
SocioeconomicStatus                 3
EducationLevel                      4
Ethnicity                           4
DiastolicBP                        60
Age                                71
SystolicBP                         90
SerumCreatinine                  1659
AlcoholConsumption               1659
PhysicalActivity                 1659
DietQuality                      1659
FastingBloodSugar                1659
HbA1c                            1659
SleepQuality                     1659
BMI                              1659
PatientID                        1659
CholesterolTotal                 1659
HemoglobinLevels                 1659
SerumElectrolytesPhosphorus      1659
SerumElectrolytesCalcium         1659
SerumElectrolytesPotassium       1659
SerumElectrolytesSodium          1659
ACR                              1659
ProteinInUrine                   1659
GFR                              1659
BUNLevels                        1659
NSAIDsUse                        1659
FatigueLevels                    1659
MuscleCramps                     1659
CholesterolLDL                   1659
CholesterolHDL                   1659
CholesterolTriglycerides         1659
Itching                          1659
QualityOfLifeScore               1659
NauseaVomiting                   1659
MedicalCheckupsFrequency         1659
HealthLiteracy                   1659
MedicationAdherence              1659
dtype: int64

In [16]:
print("Diabetes Target")
display(diabetes_df.iloc[:, -1].value_counts())

print("\nHeart Target")
display(heart_df.iloc[:, -1].value_counts())

print("\nKidney Target")
display(kidney_df.iloc[:, -1].value_counts())

Diabetes Target

diabetes
0    91500
1     8500
Name: count, dtype: int64

Heart Target

cardio
0    35021
1    34979
Name: count, dtype: int64

Kidney Target

DoctorInCharge
Confidential    1659
Name: count, dtype: int64

In [17]:
summary = pd.DataFrame({
    "Dataset": ["Diabetes", "Heart", "Kidney"],
    "Rows": [
        diabetes_df.shape[0],
        heart_df.shape[0],
        kidney_df.shape[0]
    ],
    "Columns": [
        diabetes_df.shape[1],
        heart_df.shape[1],
        kidney_df.shape[1]
    ],
    "Missing Values": [
        diabetes_df.isnull().sum().sum(),
        heart_df.isnull().sum().sum(),
        kidney_df.isnull().sum().sum()
    ],
    "Duplicate Rows": [
        diabetes_df.duplicated().sum(),
        heart_df.duplicated().sum(),
        kidney_df.duplicated().sum()
    ]
})

display(summary)

    Dataset    Rows  Columns  Missing Values  Duplicate Rows
0  Diabetes  100000        9               0            3854
1     Heart   70000       13               0               0
2    Kidney    1659       54               0               0