In [9]:
import os
print(os.getcwd())

d:\Intern Project\notebook\Preprocessing

In [10]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv("../../data/raw/diabetes_prediction_dataset.csv")
print(df.shape)
display(df.head())

(100000, 9)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [11]:
print(df.info())
print(df.isnull().sum())
print("Duplicates:",df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB
None
gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64
Duplicates: 3854

In [12]:
df=df.drop_duplicates()

gender_encoder=LabelEncoder()
smoking_encoder=LabelEncoder()

df["gender"]=gender_encoder.fit_transform(df["gender"])
df["smoking_history"]=smoking_encoder.fit_transform(df["smoking_history"])

display(df.head())

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,4,25.19,6.6,140,0
1,0,54.0,0,0,0,27.32,6.6,80,0
2,1,28.0,0,0,4,27.32,5.7,158,0
3,0,36.0,0,0,1,23.45,5.0,155,0
4,1,76.0,1,1,1,20.14,4.8,155,0

In [13]:
print(df.describe(include="all"))
print(df.dtypes)

             gender           age  hypertension  heart_disease  \
count  96146.000000  96146.000000  96146.000000   96146.000000
mean       0.416065     41.794326      0.077601       0.040803
std        0.493287     22.462948      0.267544       0.197833
min        0.000000      0.080000      0.000000       0.000000
25%        0.000000     24.000000      0.000000       0.000000
50%        0.000000     43.000000      0.000000       0.000000
75%        1.000000     59.000000      0.000000       0.000000
max        2.000000     80.000000      1.000000       1.000000

       smoking_history           bmi   HbA1c_level  blood_glucose_level  \
count     96146.000000  96146.000000  96146.000000         96146.000000
mean          2.231159     27.321461      5.532609           138.218231
std           1.879963      6.767716      1.073232            40.909771
min           0.000000     10.010000      3.500000            80.000000
25%           0.000000     23.400000      4.800000           100.000000
50%           3.000000     27.320000      5.800000           140.000000
75%           4.000000     29.860000      6.200000           159.000000
max           5.000000     95.690000      9.000000           300.000000

           diabetes
count  96146.000000
mean       0.088220
std        0.283616
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
gender                   int64
age                    float64
hypertension             int64
heart_disease            int64
smoking_history          int64
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

In [14]:
df.to_csv("../../data/processed/diabetes_processed.csv",index=False)
print("Saved successfully.")

Saved successfully.