In [2]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

df=pd.read_csv("../../data/raw/cardio_train.csv",sep=";")
print(df.shape)
display(df.head())

(70000, 13)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [3]:
print(df.info())
print(df.isnull().sum())
print("Duplicates:",df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB
None
id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64
Duplicates: 0

In [4]:
df.drop(columns=["id"],inplace=True)
df["age"]=(df["age"]/365).astype(int)
df=df.drop_duplicates()
display(df.head())

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,47,1,156,56.0,100,60,1,1,0,0,0,0

In [5]:
print(df.describe())
print(df.dtypes)

                age        gender        height        weight         ap_hi  \
count  66792.000000  66792.000000  66792.000000  66792.000000  66792.000000
mean      52.859729      1.356210    164.341748     74.521160    129.231585
std        6.803670      0.478882      8.333904     14.580675    157.649354
min       29.000000      1.000000     55.000000     10.000000   -150.000000
25%       48.000000      1.000000    159.000000     65.000000    120.000000
50%       53.000000      1.000000    165.000000     72.000000    120.000000
75%       58.000000      2.000000    170.000000     83.000000    140.000000
max       64.000000      2.000000    250.000000    200.000000  16020.000000

              ap_lo   cholesterol          gluc         smoke          alco  \
count  66792.000000  66792.000000  66792.000000  66792.000000  66792.000000
mean      97.446221      1.382725      1.236106      0.092137      0.056294
std      192.906434      0.690132      0.582063      0.289221      0.230491
min      -70.000000      1.000000      1.000000      0.000000      0.000000
25%       80.000000      1.000000      1.000000      0.000000      0.000000
50%       80.000000      1.000000      1.000000      0.000000      0.000000
75%       90.000000      2.000000      1.000000      0.000000      0.000000
max    11000.000000      3.000000      3.000000      1.000000      1.000000

             active        cardio
count  66792.000000  66792.000000
mean       0.798539      0.511933
std        0.401095      0.499861
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        1.000000      1.000000
max        1.000000      1.000000
age              int64
gender           int64
height           int64
weight         float64
ap_hi            int64
ap_lo            int64
cholesterol      int64
gluc             int64
smoke            int64
alco             int64
active           int64
cardio           int64
dtype: object

In [6]:
df.to_csv("../../data/processed/heart_processed.csv",index=False)
print("Saved successfully.")

Saved successfully.