In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd

df=pd.read_csv("../../data/raw/Chronic_Kidney_Disease_data.csv")
print(df.shape)
display(df.head())

(1659, 54)

,PatientID,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,...,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis,DoctorInCharge
0,1,71,0,0,0,2,31.069414,1,5.128112,1.676220,...,7.556302,76.076800,0,0,1,1.018824,4.966808,9.871449,1,Confidential
1,2,34,0,0,1,3,29.692119,1,18.609552,8.377574,...,6.836766,40.128498,0,0,0,3.923538,8.189275,7.161765,1,Confidential
2,3,80,1,1,0,1,37.394822,1,11.882429,9.607401,...,2.144722,92.872842,0,1,1,1.429906,7.624028,7.354632,1,Confidential
3,4,40,0,2,0,1,31.329680,0,16.020165,0.408871,...,7.077188,90.080321,0,0,0,3.226416,3.282688,6.629587,1,Confidential
4,5,43,0,1,1,2,23.726311,0,7.944146,0.780319,...,3.553118,5.258372,0,0,1,0.285466,3.849498,1.437385,1,Confidential

In [2]:
print(df.info())
print(df.isnull().sum())
print("Duplicates:",df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PatientID                      1659 non-null   int64
 1   Age                            1659 non-null   int64
 2   Gender                         1659 non-null   int64
 3   Ethnicity                      1659 non-null   int64
 4   SocioeconomicStatus            1659 non-null   int64
 5   EducationLevel                 1659 non-null   int64
 6   BMI                            1659 non-null   float64
 7   Smoking                        1659 non-null   int64
 8   AlcoholConsumption             1659 non-null   float64
 9   PhysicalActivity               1659 non-null   float64
 10  DietQuality                    1659 non-null   float64
 11  SleepQuality                   1659 non-null   float64
 12  FamilyHistoryKidneyDisease     1659 non-null   int64
 13  FamilyHistoryHypertension      1659 non-null   int64
 14  FamilyHistoryDiabetes          1659 non-null   int64
 15  PreviousAcuteKidneyInjury      1659 non-null   int64
 16  UrinaryTractInfections         1659 non-null   int64
 17  SystolicBP                     1659 non-null   int64
 18  DiastolicBP                    1659 non-null   int64
 19  FastingBloodSugar              1659 non-null   float64
 20  HbA1c                          1659 non-null   float64
 21  SerumCreatinine                1659 non-null   float64
 22  BUNLevels                      1659 non-null   float64
 23  GFR                            1659 non-null   float64
 24  ProteinInUrine                 1659 non-null   float64
 25  ACR                            1659 non-null   float64
 26  SerumElectrolytesSodium        1659 non-null   float64
 27  SerumElectrolytesPotassium     1659 non-null   float64
 28  SerumElectrolytesCalcium       1659 non-null   float64
 29  SerumElectrolytesPhosphorus    1659 non-null   float64
 30  HemoglobinLevels               1659 non-null   float64
 31  CholesterolTotal               1659 non-null   float64
 32  CholesterolLDL                 1659 non-null   float64
 33  CholesterolHDL                 1659 non-null   float64
 34  CholesterolTriglycerides       1659 non-null   float64
 35  ACEInhibitors                  1659 non-null   int64
 36  Diuretics                      1659 non-null   int64
 37  NSAIDsUse                      1659 non-null   float64
 38  Statins                        1659 non-null   int64
 39  AntidiabeticMedications        1659 non-null   int64
 40  Edema                          1659 non-null   int64
 41  FatigueLevels                  1659 non-null   float64
 42  NauseaVomiting                 1659 non-null   float64
 43  MuscleCramps                   1659 non-null   float64
 44  Itching                        1659 non-null   float64
 45  QualityOfLifeScore             1659 non-null   float64
 46  HeavyMetalsExposure            1659 non-null   int64
 47  OccupationalExposureChemicals  1659 non-null   int64
 48  WaterQuality                   1659 non-null   int64
 49  MedicalCheckupsFrequency       1659 non-null   float64
 50  MedicationAdherence            1659 non-null   float64
 51  HealthLiteracy                 1659 non-null   float64
 52  Diagnosis                      1659 non-null   int64
 53  DoctorInCharge                 1659 non-null   object
dtypes: float64(30), int64(23), object(1)
memory usage: 700.0+ KB
None
PatientID                        0
Age                              0
Gender                           0
Ethnicity                        0
SocioeconomicStatus              0
EducationLevel                   0
BMI                              0
Smoking                          0
AlcoholConsumption               0
PhysicalActivity                 0
DietQuality                      0
SleepQuality                     0
FamilyHistoryKidneyDisease       0
FamilyHistoryHypertension        0
FamilyHistoryDiabetes            0
PreviousAcuteKidneyInjury        0
UrinaryTractInfections           0
SystolicBP                       0
DiastolicBP                      0
FastingBloodSugar                0
HbA1c                            0
SerumCreatinine                  0
BUNLevels                        0
GFR                              0
ProteinInUrine                   0
ACR                              0
SerumElectrolytesSodium          0
SerumElectrolytesPotassium       0
SerumElectrolytesCalcium         0
SerumElectrolytesPhosphorus      0
HemoglobinLevels                 0
CholesterolTotal                 0
CholesterolLDL                   0
CholesterolHDL                   0
CholesterolTriglycerides         0
ACEInhibitors                    0
Diuretics                        0
NSAIDsUse                        0
Statins                          0
AntidiabeticMedications          0
Edema                            0
FatigueLevels                    0
NauseaVomiting                   0
MuscleCramps                     0
Itching                          0
QualityOfLifeScore               0
HeavyMetalsExposure              0
OccupationalExposureChemicals    0
WaterQuality                     0
MedicalCheckupsFrequency         0
MedicationAdherence              0
HealthLiteracy                   0
Diagnosis                        0
DoctorInCharge                   0
dtype: int64
Duplicates: 0

In [3]:
df.drop(columns=["PatientID","DoctorInCharge"],inplace=True)
df=df.drop_duplicates()
display(df.head())

,Age,Gender,Ethnicity,SocioeconomicStatus,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,MuscleCramps,Itching,QualityOfLifeScore,HeavyMetalsExposure,OccupationalExposureChemicals,WaterQuality,MedicalCheckupsFrequency,MedicationAdherence,HealthLiteracy,Diagnosis
0,71,0,0,0,2,31.069414,1,5.128112,1.676220,0.240386,...,4.518513,7.556302,76.076800,0,0,1,1.018824,4.966808,9.871449,1
1,34,0,0,1,3,29.692119,1,18.609552,8.377574,6.503233,...,2.202222,6.836766,40.128498,0,0,0,3.923538,8.189275,7.161765,1
2,80,1,1,0,1,37.394822,1,11.882429,9.607401,2.104828,...,5.967271,2.144722,92.872842,0,1,1,1.429906,7.624028,7.354632,1
3,40,0,2,0,1,31.329680,0,16.020165,0.408871,6.964422,...,2.176387,7.077188,90.080321,0,0,0,3.226416,3.282688,6.629587,1
4,43,0,1,1,2,23.726311,0,7.944146,0.780319,3.097796,...,6.800993,3.553118,5.258372,0,0,1,0.285466,3.849498,1.437385,1

In [4]:
print(df.describe(include="all"))
print(df.dtypes)

               Age       Gender   Ethnicity  SocioeconomicStatus  \
count  1659.000000  1659.000000  1659.00000          1659.000000
mean     54.441230     0.515371     0.71308             0.977697
std      20.549757     0.499914     1.00043             0.776686
min      20.000000     0.000000     0.00000             0.000000
25%      36.000000     0.000000     0.00000             0.000000
50%      54.000000     1.000000     0.00000             1.000000
75%      72.000000     1.000000     1.00000             2.000000
max      90.000000     1.000000     3.00000             2.000000

       EducationLevel          BMI      Smoking  AlcoholConsumption  \
count     1659.000000  1659.000000  1659.000000         1659.000000
mean         1.693189    27.620049     0.292948            9.969831
std          0.910611     7.288670     0.455252            5.798787
min          0.000000    15.033888     0.000000            0.021740
25%          1.000000    21.471449     0.000000            5.051156
50%          2.000000    27.652077     0.000000            9.951503
75%          2.000000    34.015849     1.000000           14.967100
max          3.000000    39.993532     1.000000           19.992713

       PhysicalActivity  DietQuality  ...  MuscleCramps      Itching  \
count       1659.000000  1659.000000  ...   1659.000000  1659.000000
mean           5.024247     5.028544  ...      3.525510     5.054869
std            2.866274     2.865777  ...      2.026131     2.880460
min            0.001186     0.002407  ...      0.006327     0.013697
25%            2.555038     2.558443  ...      1.820793     2.532867
50%            5.072395     4.989810  ...      3.572522     5.087086
75%            7.460563     7.428290  ...      5.254956     7.552093
max            9.998167     9.998927  ...      6.984636     9.998313

       QualityOfLifeScore  HeavyMetalsExposure  OccupationalExposureChemicals  \
count         1659.000000          1659.000000                    1659.000000
mean            49.730659             0.044002                       0.103074
std             27.827593             0.205162                       0.304147
min              0.087256             0.000000                       0.000000
25%             26.991708             0.000000                       0.000000
50%             48.970075             0.000000                       0.000000
75%             73.913997             0.000000                       0.000000
max             99.987510             1.000000                       1.000000

       WaterQuality  MedicalCheckupsFrequency  MedicationAdherence  \
count   1659.000000               1659.000000          1659.000000
mean       0.197107                  2.000336             4.947788
std        0.397934                  1.141635             2.869959
min        0.000000                  0.001082             0.005392
25%        0.000000                  1.005802             2.498119
50%        0.000000                  2.040635             4.974069
75%        0.000000                  2.947213             7.499783
max        1.000000                  3.999469             9.992345

       HealthLiteracy    Diagnosis
count     1659.000000  1659.000000
mean         5.144973     0.918626
std          2.901138     0.273492
min          0.004436     0.000000
25%          2.569561     1.000000
50%          5.182949     1.000000
75%          7.733253     1.000000
max          9.993754     1.000000

[8 rows x 52 columns]
Age                                int64
Gender                             int64
Ethnicity                          int64
SocioeconomicStatus                int64
EducationLevel                     int64
BMI                              float64
Smoking                            int64
AlcoholConsumption               float64
PhysicalActivity                 float64
DietQuality                      float64
SleepQuality                     float64
FamilyHistoryKidneyDisease         int64
FamilyHistoryHypertension          int64
FamilyHistoryDiabetes              int64
PreviousAcuteKidneyInjury          int64
UrinaryTractInfections             int64
SystolicBP                         int64
DiastolicBP                        int64
FastingBloodSugar                float64
HbA1c                            float64
SerumCreatinine                  float64
BUNLevels                        float64
GFR                              float64
ProteinInUrine                   float64
ACR                              float64
SerumElectrolytesSodium          float64
SerumElectrolytesPotassium       float64
SerumElectrolytesCalcium         float64
SerumElectrolytesPhosphorus      float64
HemoglobinLevels                 float64
CholesterolTotal                 float64
CholesterolLDL                   float64
CholesterolHDL                   float64
CholesterolTriglycerides         float64
ACEInhibitors                      int64
Diuretics                          int64
NSAIDsUse                        float64
Statins                            int64
AntidiabeticMedications            int64
Edema                              int64
FatigueLevels                    float64
NauseaVomiting                   float64
MuscleCramps                     float64
Itching                          float64
QualityOfLifeScore               float64
HeavyMetalsExposure                int64
OccupationalExposureChemicals      int64
WaterQuality                       int64
MedicalCheckupsFrequency         float64
MedicationAdherence              float64
HealthLiteracy                   float64
Diagnosis                          int64
dtype: object

In [5]:
df.to_csv("../../data/processed/kidney_processed.csv",index=False)
print("Saved successfully.")

Saved successfully.